name: MISSION! Devops
on:
  label:
    types:
      - created
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
    #      - ".github/**"
    branches:
      - main
      - dev
      - "releases/**"
env:
  VERSION: 'beta2.0'
  DOCKER_USERNAME: lomofu
  DOCKER_TOKEN: f1089bbc-4e69-4c80-a986-9cb483e5983f

jobs:
  Build-Mission-App:
    if: ${{ contains(github.event.head_commit.message, '[build]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up The Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 17.4.0

      - name: List Directory
        run: ls -a

      - name: Install Dependencies With NPM
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lomofu/mission:${{ env.VERSION }}
